### ISSUE TITLE
跪求大神开源 部门自定义 照相功能

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidMediaStreaming#147]
在小米4c您的机型是完美的支持，而网上的camera2demo 总是失败 安全权限什么的，而 camerademo无法设置参数 。以前的手机都是可以的，您们是怎么做到的。求大神指点

**Comment by jpxiong** [comment]
你可以贴一下 camera2demo 的操作 camera 的相关代码，我可以帮你看看
