### ISSUE TITLE
推流时走到onRecordAudioFailedHandled，后重新推流失败

### ISSUE THREAD

**Issue by huazi0923** [pili-engineering/PLDroidMediaStreaming#148]
正常推流一段时间，经常报onRecordAudioFailedHandled，然后重新推流，还是报onRecordAudioFailedHandled，然后重新推流两次就不再重新推了，是不是跟生命周期有关，我是按照demo里的生命周期写的？

**Comment by jpxiong** [comment]
onRecordAudioFailedHandled

怎么实现的？

**Comment by huazi0923** [comment]
只是return了一下，代码如下：
return mCameraStreamingManager.startStreaming();

**Comment by jpxiong** [comment]
请参考 demo 的实现。有两种处理方式，要么提醒用户切换到纯视频推流，要么终止推流。如果收到这个消息，代表音频无法正常获取了。

**Comment by huazi0923** [comment]
恩，那请问一下纯视频推流是否播放端就没有声音了？我测试的是没有的

**Comment by jpxiong** [comment]
纯视频推流意识就是只有视频，没有音频，播放肯定没有声音。
