### ISSUE TITLE
1.7.1demo开始推流提示IOERROR

### ISSUE THREAD

**Issue by jjdxmashl** [pili-engineering/PLDroidMediaStreaming#159]
{"id":"z1.huigoufang.testlive1","createdAt":"2016-08-01T07:57:09.922Z","updatedAt":"2016-08-01T07:57:09.922Z","title":"testlive1","hub":"huigoufang","disabledTill":0,"disabled":false,"publishKey":"45799132b61e8559","publishSecurity":"expiry_sk","hosts":{"publish":{"rtmp":"pili-publish.oawr9cz74.bkt.clouddn.com"},"live":{"hdl":"pili-live-hdl.oawr9cz74.bkt.clouddn.com","hls":"pili-live-hls.oawr9cz74.bkt.clouddn.com","http":"pili-live-hls.oawr9cz74.bkt.clouddn.com","rtmp":"pili-live-rtmp.oawr9cz74.bkt.clouddn.com","snapshot":"pili-live-snapshot.oawr9cz74.bkt.clouddn.com"},"playback":{"hls":"10002ry.playback1.z1.pili.qiniucdn.com","http":"10002ry.playback1.z1.pili.qiniucdn.com"},"play":{"http":"pili-live-hls.oawr9cz74.bkt.clouddn.com","rtmp":"pili-live-rtmp.oawr9cz74.bkt.clouddn.com"}}}

日志

E/pldroid_core_packet: pili_stream_push_open failed. ret=-1
E/pldroid_core_packet: ERROR: init error --
E/Muxer: PLMuxer.prepare(): rc
E/Muxer: Init streaming core failed.

**Comment by jpxiong** [comment]
v2.0.0 支持 expiry_sk 鉴权模式，之前的版本不支持。

**Comment by mahongli05** [comment]
09-10 15:17:36.144 20287-1800/com.qiniu.pili.droid.streaming.demo E/pldroid_core_packet: pili_stream_push_open failed. ret=-1
09-10 15:17:36.144 20287-1800/com.qiniu.pili.droid.streaming.demo D/pldroid_core_packet: initialize ret=-1
09-10 15:17:36.144 20287-1800/com.qiniu.pili.droid.streaming.demo E/pldroid_core_packet: ERROR: init error --
09-10 15:17:36.144 20287-1800/com.qiniu.pili.droid.streaming.demo E/Muxer: PLMuxer.prepare(): rc
09-10 15:17:36.144 20287-1800/com.qiniu.pili.droid.streaming.demo I/MediaStreamingManager: muxerStatusUpdate muxerState:IOERROR,isNeedUpdateProfile:false
09-10 15:17:36.144 20287-1800/com.qiniu.pili.droid.streaming.demo E/Muxer: Init streaming core failed.

用的2.0的demo，一样出现这个问题。啥原因？

**Comment by jjdxmashl** [comment]
我遇到的是鉴权问题
https://pili.qiniu.com   需要到霹雳流这里设置为静态推流方式 static，限时推流我没有能测试通过，也就是创建流的时候需要创建静态的static
