### ISSUE TITLE
onPreviewSizeSelected的具体用法？

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidMediaStreaming#161]
StreamingSessionListener中的onPreviewSizeSelected的具体用法是什么？感觉返回什么类型的Size都没有用啊？

**Comment by jpxiong** [comment]
https://github.com/pili-engineering/PLDroidMediaStreaming/wiki/5-%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#5.1.3
