### ISSUE TITLE
直播画面不能全屏显示

### ISSUE THREAD

**Issue by winneryong** [pili-engineering/PLDroidMediaStreaming#177]
在小米4和魅族note2上都试了，不能全屏显示预览。
请见图片。
![device-2016-09-09-145028](https://cloud.githubusercontent.com/assets/665637/18378132/ad8c0c90-769d-11e6-8d01-1c8cf99c1a40.png)

**Comment by ulexzhong** [comment]
aspectFrameLayout.setShowMode(AspectFrameLayout.SHOW_MODE.FULL);

**Comment by winneryong** [comment]
@ulexzhong 好了，非常感谢！
