### ISSUE TITLE
直播手机端截屏横屏

### ISSUE THREAD

**Issue by Lei13** [pili-engineering/PLDroidMediaStreaming#183]
你好，我在手机端通过GLSurfaceview截屏（为了有滤镜效果，截帧不含滤镜），截下来顺时针旋转了90度，图片检测并没有旋转角度（猜测应该是横屏了），初始化设置了 .setEncodingOrientation(StreamingProfile.ENCODING_ORIENTATION.PORT)的，请问知道这是怎么回事么？

**Comment by jpxiong** [comment]
```
setEncodingOrientation(StreamingProfile.ENCODING_ORIENTATION.PORT)
```
是针对编码的。

旋转了 90 度，应该是 Camera Display 的方向被更新了导致。

**Comment by Lei13** [comment]
嗯，好的，那怎么获取cameraParemater来设置displayOrienzation呢？CameraStreamingSetting并没有暴露出来啊
