### ISSUE TITLE
url is invalid

### ISSUE THREAD

**Issue by BaeBae33** [pili-engineering/PLDroidMediaStreaming#216]
打印的url是rtmp://xx.xx.x.xxx:1935/live/LIVE_30_1482146129?nonce=1482152255&token=rVWJ4rTQgq_wEENd3zMYQiRHHV0=
用旧版是可以推的，新版却不行

**Comment by nguyenanhthai** [comment]
Same issue

**Comment by Jhuster** [comment]
token 是怎么签算的？跟 URL 本身是否有关系，如果有，请关闭掉 DNS 预解析，因为预解析改变了 URL

```
StreamingProfile.setDnsManager(null)
```
