### ISSUE TITLE
有外部采集的demo吗？

### ISSUE THREAD

**Issue by jiaminfu** [pili-engineering/PLDroidMediaStreaming#262]
有外部采集的demo吗？

**Comment by HugoLipeng** [comment]
使用说明：https://github.com/pili-engineering/PLDroidMediaStreaming/wiki/5-%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#58-streamingmanager

demo里面  ImportStreamingActivity 这个类
