### ISSUE TITLE
推流端预览左右两边有黑色

### ISSUE THREAD

**Issue by qidianli** [pili-engineering/PLDroidMediaStreaming#310]
1布局 
<com.qiniu.pili.droid.streaming.widget.AspectFrameLayout
        android:id="@+id/cameraPreview_afl"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_centerHorizontal="true"
        android:layout_alignParentTop="true">
        <cn.com.qlwb.qiluyiidan.toolbox.live.view.CameraPreviewFrameView
            android:id="@+id/cameraPreview_surfaceView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center" />
        <include layout="@layout/focus_indicator"/>
    </com.qiniu.pili.droid.streaming.widget.AspectFrameLayout>
2 代码：
  AspectFrameLayout afl = (AspectFrameLayout) findViewById(R.id.cameraPreview_afl);
        // Decide FULL screen or real size
        afl.setShowMode(AspectFrameLayout.SHOW_MODE.FULL);
        //GLSurfaceView glSurfaceView = (GLSurfaceView) findViewById(R.id.cameraPreview_surfaceView);
        CameraPreviewFrameView cameraPreviewFrameView =
                (CameraPreviewFrameView) findViewById(R.id.cameraPreview_surfaceView);
        cameraPreviewFrameView.setListener(this);

**Comment by BoleLiu** [comment]
AspectFrameLayout 已被废弃，请参考 demo 的实现哈
