### ISSUE TITLE
最新Demo运行不起来

### ISSUE THREAD

**Issue by lydlovezjr** [pili-engineering/PLDroidMediaStreaming#330]
<img width="960" alt="企业微信截图_20220105170658" src="https://user-images.githubusercontent.com/19246347/148190870-81d7b5d2-16dd-4bd9-8909-b783117458f6.png">

**Comment by lydlovezjr** [comment]
还望尽快修复一下,谢了

**Comment by BoleLiu** [comment]
好的，收到，该部分代码用于搜集 Demo 上的崩溃信息，不影响主体功能的使用，您可以先注释掉，我们后续会尽快更新的

**Comment by BoleLiu** [comment]
@lydlovezjr 好的，收到，该部分代码用于搜集 Demo 上的崩溃信息，不影响主体功能的使用，您可以先注释掉，我们后续会尽快更新的

**Comment by BoleLiu** [comment]
@lydlovezjr 已更新
